/* Replaces bios/lineavars.S storage. GPL-2.0-or-later. */
#include "emutos.h"
#include "lineavars.h"
#include "vdi_defs.h"
MCS mouse_cursor_save;
MCS ext_mouse_cursor_save;
UWORD v_planes;
UWORD v_lin_wr;
UWORD v_cel_ht;
UWORD v_cel_mx;
UWORD v_cel_my;
UWORD v_cel_wr;
UWORD v_cur_cx;
UWORD v_cur_cy;
UWORD V_REZ_HZ;
UWORD V_REZ_VT;
UWORD BYTES_LIN;
WORD DEV_TAB[45];
WORD MOUSE_BT;
WORD X1, Y1, X2, Y2;
WORD WRT_MODE;
WORD COLBIT0, COLBIT1, COLBIT2, COLBIT3;
WORD CLIP;
WORD XMINCL, XMAXCL, YMINCL, YMAXCL;
UWORD *PATPTR;
UWORD PATMSK;
WORD XDDA;
UWORD DDAINC;
WORD SCALDIR;
WORD MONO;
WORD SOURCEX, SOURCEY;
WORD DESTX, DESTY;
UWORD DELX, DELY;
const UWORD *FBASE;
WORD FWIDTH;
WORD STYLE;
WORD LITEMASK, SKEWMASK;
WORD WEIGHT;
WORD ROFF, LOFF;
WORD SCALE;
WORD CHUP;
WORD TEXTFG;
WORD *SCRTCHP;
WORD SCRPT2;
const Fonthead *CUR_FONT;
const UWORD *v_fnt_ad;
const UWORD *v_off_ad;
UWORD v_fnt_nd;
UWORD v_fnt_st;
UWORD v_fnt_wr;
const Fonthead *def_font;
const Fonthead *font_ring[4];
WORD font_count;
ETV_TIMER_T tim_addr;
ETV_TIMER_T tim_chain;
WORD REQ_COL[16][3];
WORD req_col2[240][3];
WORD line_cw;
WORD num_qc_lines;
WORD val_mode, chc_mode, loc_mode, str_mode;
WORD SIZ_TAB[15];
WORD INQ_TAB[45];
WORD *CONTRL, *INTIN, *PTSIN, *INTOUT, *PTSOUT;
WORD LN_MASK, LSTLIN;
WORD TERM_CH;
WORD COPYTRAN;
WORD MFILL;
Vwk *CUR_WORK;
WORD (*SEEDABORT)(void);
WORD GCURX;
WORD GCURY;
WORD HIDE_CNT;
WORD     newx;
WORD     newy;
UBYTE    draw_flag;
UBYTE    mouse_flag;
UBYTE    cur_ms_stat;
Vwk phys_work;
PFVOID user_but,user_cur,user_mot;
struct { WORD xhot,yhot,planes,bg_col,fg_col; UWORD maskdata[32]; } mouse_cdb;
/* Console variables supplied by lineavars.S on the Motorola targets. */
WORD v_col_bg,v_col_fg,v_cur_of,disab_cnt,sav_cur_x,sav_cur_y;
UBYTE *v_cur_ad;
UBYTE v_cur_tim,v_period,v_stat_0;
